name: boulderbuds
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Firebase
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0

  #BLoC
  flutter_bloc: ^8.1.5

  #Custom Repository
  user_repository: 
    path: packages/user_repository
  gym_repository: 
    path: packages/gym_repository

  #Other
  equatable: ^2.0.5
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.9
  image: ^4.1.7
  multi_dropdown: ^2.1.4
  uuid: ^4.4.0
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

